# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
