# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_issue_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='index',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
