# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-14 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_project'),
        ('issues', '0005_auto_20161213_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='tags',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
