# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_closestate'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('closed', models.BooleanField(default=False)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Issue')),
            ],
        ),
        migrations.RemoveField(
            model_name='closestate',
            name='issue',
        ),
        migrations.DeleteModel(
            name='CloseState',
        ),
    ]
