# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_auto_20161219_0442'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
