# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 16:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0012_issuestate_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.Issue')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='issuestate',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='issuestate',
            name='id',
        ),
        migrations.RemoveField(
            model_name='issuestate',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='issuestate',
            name='owner',
        ),
        migrations.AddField(
            model_name='issuestate',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issues.Event'),
            preserve_default=False,
        ),
    ]
