# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_auto_20161220_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IssueState',
            new_name='State',
        ),
    ]
