# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import tags.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', tags.models.LowerCaseCharField(max_length=64)),
                ('color', models.CharField(max_length=7)),
            ],
        ),
    ]
