# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 19:31
from __future__ import unicode_literals

import colorful.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=colorful.fields.RGBColorField(),
        ),
    ]
