# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0013_auto_20161220_1623'),
        ('comments', '0002_auto_20161213_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='id',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='owner',
        ),
        migrations.AddField(
            model_name='comment',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='issues.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='edit_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
