# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='issue_index',
            field=models.IntegerField(default=1),
        ),
    ]
