# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-19 04:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_issue_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='project',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
